name: NetherManhunt2
version: '${project.version}'
main: si.f5.actedsauce.nethermanhunt2.NetherManhunt2
api-version: '1.20'
authors: [Acted]
description: Great Manhunt in Netheｒ!!!!!!!!!!!
commands:
  joinhunter:
    aliases: [jh]
    description: Join to the hunter team.
  joinrunner:
    aliases: [jr]
    description: Join to the runner team.
  leaveteam:
    aliases: [lt]
    description: Leave from a team.
  start:
    aliases: [st]
    description: Start the game.
  suspension:
    aliases: [su]
    description: Suspension the game.


